#################################################################
#                                                               #
#                                                               #
# THIS FILE IS COPIED FROM THE BOILERPLATE DIRECTORY,           #
# DO NOT EDIT IT OR YOU WILL LOSE YOUR CHANGES.                 #
# MAKE CHANGES IN THE TOP LEVEL services/boilerplate DIRECTORY. #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                  DO NOT EDIT THIS FILE                        #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                  DO NOT EDIT THIS FILE                        #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                  DO NOT EDIT THIS FILE                        #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#################################################################
# Canonical source: services/boilerplate/service_handler.py
# — regenerate with 'make boilerplate'

"""Service handler utils for TSFM models"""

import importlib
import logging
import os
import pathlib
from typing import Any, Dict, Optional, Union

import transformers
from transformers import (
    AutoConfig,
    AutoModel,
    PretrainedConfig,
    PreTrainedModel,
)

import tsfm_public
from tsfm_public.toolkit.hf_util import register_config

from . import TSFM_ALLOW_LOAD_FROM_HF_HUB


LOCAL_FILES_ONLY = not TSFM_ALLOW_LOAD_FROM_HF_HUB


LOGGER = logging.getLogger(__file__)


# Security: Base allowlist of trusted module prefixes
_BASE_ALLOWED_MODULE_PREFIXES = (
    "tsfm_public.",
    "tsfminference.",
    "tsfmfinetuning.",
    "transformers.",
)

# Security: Allow additional trusted module prefixes via environment variable
# Format: comma-separated list of module prefixes, e.g., "mycompany.models.,custom.modules."
# Each prefix MUST end with a dot to ensure exact module path matching
_ADDITIONAL_ALLOWED_MODULE_PREFIXES = os.getenv("TSFM_ADDITIONAL_MODULE_PREFIXES", "")


def _validate_and_parse_additional_prefixes(prefixes_str: str) -> tuple:
    """Parse and validate additional module prefixes from environment variable.

    Security: Enforces that each prefix ends with a dot to prevent overly broad matches.
    For example, "mycompany." is safe, but "mycompany" would match "mycompany_evil".

    Args:
        prefixes_str: Comma-separated string of module prefixes

    Returns:
        Tuple of validated prefixes

    Raises:
        ValueError: If any prefix doesn't end with a dot
    """
    if not prefixes_str.strip():
        return ()

    prefixes = []
    for prefix in prefixes_str.split(","):
        prefix = prefix.strip()
        if not prefix:
            continue

        if not prefix.endswith("."):
            raise ValueError(
                f"Security: Additional module prefix '{prefix}' must end with a dot ('.'). "
                f"This ensures exact module path matching and prevents overly broad allowlists. "
                f"Example: use 'mycompany.models.' instead of 'mycompany.models'"
            )

        prefixes.append(prefix)

    return tuple(prefixes)


_additional_prefixes = _validate_and_parse_additional_prefixes(_ADDITIONAL_ALLOWED_MODULE_PREFIXES)

# Combine base and additional prefixes
ALLOWED_MODULE_PREFIXES = _BASE_ALLOWED_MODULE_PREFIXES + _additional_prefixes

if _additional_prefixes:
    LOGGER.info(
        f"Additional module prefixes enabled: {_additional_prefixes}. Ensure these modules are from trusted sources."
    )


def _validate_module_path(module_path: str) -> None:
    """Validate that module_path is from an allowed prefix.

    Args:
        module_path (str): The module path to validate.

    Raises:
        ValueError: If module_path is not from an allowed prefix.
    """
    if not any(module_path.startswith(prefix) for prefix in ALLOWED_MODULE_PREFIXES):
        raise ValueError(
            f"Module path '{module_path}' is not allowed. "
            f"Only modules starting with {ALLOWED_MODULE_PREFIXES} are permitted for security reasons."
        )


def load_config(
    model_path: Union[str, pathlib.Path],
    model_type: Optional[str] = None,
    model_config_name: Optional[str] = None,
    module_path: Optional[str] = None,
    **extra_config_kwargs: Dict[str, Any],
) -> PretrainedConfig:
    """Load configuration

    Attempts to load the configuration, if it is not loadable, then we register it with the AutoConfig mechanism.

    Args:
        model_path (pathlib.Path): The path from which to load the config.
        model_type (Optional[str], optional): The type of the model, from the model implementation. Defaults to None.
        model_config_name (Optional[str], optional): The name of configuration class for the model. Defaults to None.
        module_path (Optional[str], optional): Python module path that can be used to load the
            config/model. Defaults to None.

    Returns:
        PretrainedConfig: The configuration object corresponding to the pretrained model.
    """
    # load config first try autoconfig, if not then we register and load
    try:
        conf = AutoConfig.from_pretrained(model_path, local_files_only=LOCAL_FILES_ONLY, **extra_config_kwargs)
    except (KeyError, ValueError) as exc:  # determine error raised by autoconfig
        if model_type is None or model_config_name is None or module_path is None:
            raise ValueError("model_type, model_config_name, and module_path should be specified.") from exc

        register_config(model_type, model_config_name, module_path)
        conf = AutoConfig.from_pretrained(model_path, local_files_only=LOCAL_FILES_ONLY, **extra_config_kwargs)

    return conf


def _get_model_class(config: PretrainedConfig, module_path: Optional[str] = None) -> type:
    """Helper to find model class based on config object

    First the module_path will be checked if it can be loaded in the current environment. If not
    then the transformers library will be used.

    Args:
        config (PretrainedConfig): HF configuration for the model.
        module_path (Optional[str], optional): Python module path that can be used to load the
            config/model. Defaults to None.

    Raises:
        AttributeError: Raised if the module at module_path cannot be loaded.
        AttributeError: If the architecture provided by the config cannot be loaded from
            the module.
        ValueError: Raised when module_path is not from an allowed prefix.

    Returns:
        type: The class for the model.
    """
    if module_path is not None:
        # safe b/c mp still has to be in ALLOWED_MODULE_PREFIXES
        mp = module_path + "." if not module_path.endswith(".") else module_path
        _validate_module_path(mp)
        try:
            mods = [importlib.import_module(module_path)]
        except ModuleNotFoundError as exc:
            raise AttributeError("Could not load module '{module_path}'.") from exc
    else:
        mods = [transformers, tsfm_public]
        # Validate module_path for security
        # not needed b/c we know we are loading from trusted sources
        # _validate_module_path(module_path)

    # get architecture from model config
    architectures = getattr(config, "architectures", [])
    for arch in architectures:
        model_class = None
        for mod in mods:
            model_class = getattr(mod, arch, None)
            if model_class is not None:
                return model_class
        raise AttributeError(f"Could not load model class for architecture '{arch}'.")

        # try:
        #     model_class = getattr(mod, arch)
        #     return model_class
        # except AttributeError as exc:
        #     # catch specific error import error or attribute error
        #     raise AttributeError(f"Could not load model class for architecture '{arch}'.") from exc


def load_model(
    model_path: Union[str, pathlib.Path],
    config: Optional[PretrainedConfig] = None,
    module_path: Optional[str] = None,
) -> PreTrainedModel:
    """Load a pretrained model.
    If module_path is provided, load the model using the provided module path.

    Args:
        model_path (Union[str, pathlib.Path]): Path to a location where the model can be loaded.
        config (Optional[PretrainedConfig], optional): HF Configuration object. Defaults to None.
        module_path (Optional[str], optional): Python module path that can be used to load the
            config/model. Defaults to None.

    Raises:
        ValueError: Raised if loading from a module_path and a configuration object is not provided.

    Returns:
        PreTrainedModel: The loaded pretrained model.
    """

    if module_path is not None and config is None:
        return ValueError("Config must be provided when loading from a custom module_path")

    if config is not None:
        model_class = _get_model_class(config, module_path=module_path)
        LOGGER.info(f"Found model class: {model_class.__name__}")
        return model_class.from_pretrained(
            model_path,
            config=config,
            local_files_only=LOCAL_FILES_ONLY,
            device_map=None,  # disable meta-tensors
            low_cpu_mem_usage=False,
        )

    return AutoModel.from_pretrained(
        model_path,
        local_files_only=LOCAL_FILES_ONLY,
        device_map=None,  # disable meta-tensors
        low_cpu_mem_usage=False,
    )
