#################################################################
#                                                               #
#                                                               #
# THIS FILE IS COPIED FROM THE BOILERPLATE DIRECTORY,           #
# DO NOT EDIT IT OR YOU WILL LOSE YOUR CHANGES.                 #
# MAKE CHANGES IN THE TOP LEVEL services/boilerplate DIRECTORY. #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                  DO NOT EDIT THIS FILE                        #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                  DO NOT EDIT THIS FILE                        #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                  DO NOT EDIT THIS FILE                        #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#                                                               #
#################################################################
# Canonical source: services/boilerplate/service_handler.py
# — regenerate with 'make boilerplate'

# Copyright contributors to the TSFM project
#

try:
    # Local
    from ._version import __version__, __version_tuple__  # noqa: F401 # unused import
except ImportError:
    __version__ = "unknown"
    __version_tuple__ = (0, 0, __version__)

# Made with Bob
