python ttm_pretrain_sample.py  --context_length 512 \
                               --forecast_length 96 \
                               --patch_length 64 \
                               --batch_size 16 \
                               --num_layers 3 \
                               --decoder_num_layers 3 \
                               --dropout 0.2 \
                               --head_dropout 0.2 \
                               --early_stopping 1 \
                               --adaptive_patching_levels 0 \
                               --num_epochs 10 \
                               --differencing 1 \
                               --diff_init_strategy zero \
